### PR TITLE
Hover for custom analyzers

### PR DESCRIPTION
**Pull request by ManuelArno**

### CODE REVIEW

**Comment by ManuelArno** [comment]
Hey @ankane,

can you help me with this one?

Kind regards

**Comment by ManuelArno** [comment]
https://www.bountysource.com/issues/40447349-display-data-about-custom-analyzers

**Comment by ankane** [comment]
Hey @ManuelArno, I have a lot on my plate, so I won't be able to be a regular contributor. Just wanted to add a little value where I could :)

**Comment by ManuelArno** [comment]
Sorry for having been a bit too pushy there, know you are probably wishing to have infinite amounts of hands to finish all your work.

**Pull request merged**
